branches:
  except:
  - localization
osx_image: xcode11.1
language: objective-c
xcode_workspace: Zap.xcworkspace
xcode_scheme: Zap
cache: bundler
addons:
  homebrew:
    packages:
    - graphicsmagick
git:
  quiet: true
  depth: 3
notifications:
  email:
    on_success: never
    on_failure: change
install:
  - bundle install
  - carthage bootstrap --platform iOS
stages:
  - test
  - name: deploy
    #if: 'branch = master AND tag IS present'
jobs:
  include:
#    - stage: test        
#      script: bundle exec fastlane tests
#      after_success:
#        - bash <(curl -s https://codecov.io/bash) -J 'Library' -J 'Lightning'
    - stage: deploy
      script: bundle exec fastlane testnet
      name: "Deploy Testnet"
#    - script: bundle exec fastlane mainnet
#      name: "Deploy Mainnet"
#    - script: bundle exec fastlane release
#      name: "Deploy Appstore"
env:
global:
  # MATCH_GIT_BASIC_AUTHORIZATION
  secure: mBiY02QOHBO6+zaJ7fsxgO2KKwqJqc6CsqcAEbfZpzcv2DugnTgcBp9+R4vSASfJGTOjSojUdtzudeVF2cg+ZnMr/Dk+zOQ5EqyjjilYCci3qEkUjwr/6gblwW2uugmoGTkvdwvwTymBTpEfuHfuzsYgbybEWOIvJ8/ySHQYyUMPUMfSHwfD//l9SRCuHZeyQPoEK16USZInZtVniEdQ40ROWcyzmtb77L5BIDQZ6pBODl8rtIjS8hl/SR+i3sXsW8CES8GXvjKqsiO4p4cujShkCFY2HOPaAL32umeXPUnRPhFsqeDi9dsqi7KR8GqQ8vTBJkymaf4U3+ew+1iuOWZqOFqBR56+74xl2OBQSKUei/Ek31b65xsFAJ9pVJ1XgHxgNZ70kJZWlRR4auX1BxtuzxnFtlG4s9s2lkT3eizCldTTrwDFLTQ8U18p3X55CyfzsCCDu+NBaDW+yDm6l+Bnu5X9k5rMV8U2gHvBbsQ4z7g0ZMyTJuK7Ej8HNDYIb2Etzvztew9p+lbYUQLON8EVuFZmcTy32LhyxObuJzdEWFAx+JwwBYipMy1XQnd0xRZPRoag7L+HptEOiroB6NCIjFnalvTjnFE0dUulLOkXVyYca9fsL35enherFMKlTMKa3od5e1DiJXaZdFlVrt+v9CpZTyLFdcL4YYWBhHo=
  # MATCH_PASSWORD
  secure: RQ71U9thQM8siYKWuxN6JCXD14g3e8DE+sIpgQ8uq5rAEhCeSq6OdlT2dTkO+SvUxx71dyN+UqWBBgsi96nEzejU4OeciAipsxkVXLdK5KcBe16ksuCQuIh/FHPzagpFsWQbkNc27SNr4z8eNHUF8tP6PbolFQARa//2GGiGyZvmiOUasRJI+Q4BBNEcRzd+d5HqD281CU60bZX61PpOf5/rnkewHrzb2oJavna3hdIaAb4eoOY1dm4eatei149tmmRNq4WUratRR4IrbS/mMojV6f2jCGdJPffMvFrC672quTrA9ccZctOauBoHqNrwL8yjXSH4DkABeiyV9qbCBmVjHiTf+j+yNr6pQncdnrEfmfFIe5G33zpqPHBqz/GBVnN7tkCD1UBZJsUw1HvN+kboDNdHG8Zw6hMJn+b08PttAK+Cg+PWIHnqf/GksD3zNHXv8OULdN2sgdLpld3RCKXBLISRomlTj3wqLYIk1u0vuIgdMfTo17wrDM943xOVSFiMCiq4i/QmgLyjkAEW7F1ug3Kj5Xbfa2IIf0vY4CjWUBmak3Y0ojbxVv/CdjSWqP7gMmn1iMBYjqL9/GgG+p6to/XU4CviY9SCOBNQcC0KrdFG3fg08NveLseOaBUYedxCJSFUzCHAvdxoiIhcT49M7MIdmjtu+hIgxoFDCYo=

