osx_image: xcode9.4 
language: objective-c
xcode_workspace: Zap.xcworkspace
xcode_scheme: Zap
cache: bundler
git:
  quiet: true
  depth: 3
notifications:
  email:
    on_failure: change
script:
  - xcodebuild -showBuildSettings -workspace Zap.xcworkspace -list
  - bundle exec fastlane tests
