branches:
  except:
  - localization
osx_image: xcode11.1
language: objective-c
xcode_workspace: Zap.xcworkspace
xcode_scheme: Zap
cache: bundler
addons:
  homebrew:
    packages:
    - graphicsmagick
git:
  quiet: true
  depth: 3
notifications:
  email:
    on_success: never
    on_failure: change
install:
  - bundle install
  - carthage bootstrap --platform iOS
stages:
  - test
  - name: deploy
    #if: 'branch = master AND tag IS present'
jobs:
  include:
#    - stage: test        
#      script: bundle exec fastlane tests
#      after_success:
#        - bash <(curl -s https://codecov.io/bash) -J 'Library' -J 'Lightning'
    - stage: deploy
      script: bundle exec fastlane testnet
      name: "Deploy Testnet"
#    - script: bundle exec fastlane mainnet
#      name: "Deploy Mainnet"
#    - script: bundle exec fastlane release
#      name: "Deploy Appstore"
env:
  global:
  # MATCH_GIT_BASIC_AUTHORIZATION
  - secure: TC+Vfo4vq/XBPOhAiLgaM+lLoDthf8Fkin1HEGmqw+la0Z16zn2jo6dSobOS9MKF/KeBwx8OAk0FX4LCPP9tTRiJhZP6/PwCIpGsdg4ahWnu0MtsJs7y5Qo07sSd+fkUMkxDdBWCGLu7d09sD5aIkcymlFIlfn+AY4lwBDDzDDSZt/jSSu4Io+zMr5UpGk4SdrcYn1ZmdJBaEKTGZal7MIm5xm3LUQSqrqo2NCRaxARHNYFhGcBgXGysO3Poknuh7Aw5Fw5tVx+eX2K1dza67RTCjef4IgqlX3z0AN6KEJEJF7WotS5t0gc3Xup85pxdPj7HyZc15B120PcG+iVcHi4uCVA+eYFal3btv2cPDin/gqVnompd8UkV/RGnqQ1KbwbStijGLZVArmkMnkwxrQEDyuGNhuOQyXFIBngHEXAF+skb89nQjpILnGDbEzJIIojYCMraeJgHZYBIdFRLgRNhasYCgRBfadrxoQFSGFM1hmFmRK9Q/rKBG069pfSCuO4yHow+QKZ7WGykhr8p3pjhhk27VXkFdpFbpM2xq/JflyFcwYtXN1HFX3Ue+00qwfiCT7Ba67mfWGEkDm8xVD+26Fzve8ufvVZ+SY+1AskU+KhRtjM+Rw5O+QS5QqRzGPBqoJOkSuNFu54rhZ9fM8Twaq9z3ZQTh6K8c/wtLUo=
  # MATCH_PASSWORD
  - secure: RQ71U9thQM8siYKWuxN6JCXD14g3e8DE+sIpgQ8uq5rAEhCeSq6OdlT2dTkO+SvUxx71dyN+UqWBBgsi96nEzejU4OeciAipsxkVXLdK5KcBe16ksuCQuIh/FHPzagpFsWQbkNc27SNr4z8eNHUF8tP6PbolFQARa//2GGiGyZvmiOUasRJI+Q4BBNEcRzd+d5HqD281CU60bZX61PpOf5/rnkewHrzb2oJavna3hdIaAb4eoOY1dm4eatei149tmmRNq4WUratRR4IrbS/mMojV6f2jCGdJPffMvFrC672quTrA9ccZctOauBoHqNrwL8yjXSH4DkABeiyV9qbCBmVjHiTf+j+yNr6pQncdnrEfmfFIe5G33zpqPHBqz/GBVnN7tkCD1UBZJsUw1HvN+kboDNdHG8Zw6hMJn+b08PttAK+Cg+PWIHnqf/GksD3zNHXv8OULdN2sgdLpld3RCKXBLISRomlTj3wqLYIk1u0vuIgdMfTo17wrDM943xOVSFiMCiq4i/QmgLyjkAEW7F1ug3Kj5Xbfa2IIf0vY4CjWUBmak3Y0ojbxVv/CdjSWqP7gMmn1iMBYjqL9/GgG+p6to/XU4CviY9SCOBNQcC0KrdFG3fg08NveLseOaBUYedxCJSFUzCHAvdxoiIhcT49M7MIdmjtu+hIgxoFDCYo=
  # ITUNESCONNECT_USER
  - secure: Sis8YqpmgyXsb3JD5eV/Q1ifKIfRtMJI3Mm4b3d5mSkUeGpE5AXaBET6/CD6ASnSPRggGTuIeZhkygGW/xEt4XUO2GSUf7tzOcPJHHk0myNRGdV3YQV2OpRu/swn710b2EdesWjNyN34Dxb7uGIoNexCNigA4N7KhQWELxOvgaS/aUgvlw9rjID9pfCqqLOa4DiSG+BKrqfdJoT/MmaaRxO2GcFdXvxOOUPUi6AUEakhFVMUgptje32J4/VlgHFxv2xNadV2NrNO595TYA6jWGjjN3Gn55Gt/ZLjJXrVslUsKnJtM3w446z+Ndray1sPXlZbBzVN6ofjw37zQ12kTuod7NTVSiS0JRu4VijWpp0/UUAXPxt+KiBAervItlercmuJVfC7Sn7Jd3g0pi97U9NDqFd3WCtJKXl6tze0E67oX543JrUUpa1e8TMhrBHES6tBVpHN4g9u1lQNJT933SzS/xU9rPrzNF0KZip9C1aLOa+gWXoZEgKBIlGiGzdvVZOLouSvaY487CSFpMV3ILX/zWF4WmmkmkW5IyWLGjks00DUiQfwz3hlMuz1cJPAllc9hSXS3f/M7T07xKqv8/d1iqtzjbFMAarWDRNAK6q0C46zxqn2LgR3zG0+alP31Z/vqAA5+3tv3EVBIV2W5N2Au4HoI/ftNMh7GtylAiA=
  # FASTLANE_PASSWORD
  - secure: lZBq5BrNgEic7tNuzSzfE69jYJ4tvnob+bmLLOZ8RG1GlhYX5i18hVhRgoCWaRgQbv2MpWCKJoor32pGsiDMnROQKhYPbhUJcIRc90UvZ7te9AK6umckg5oUny3YZ0+9Stvj8h3nszheH7VV+uhU5ZmybNHiRGHQ87E0NsaaCfgAX5rPneY5Yi20HCRCfNcLEM1cKFA5TD5ggnKnLu6gFantMhgMhFOaRIhqDDfZnjkILmTiLdAUrNK/aw0zxbbJHklvq7GeFuxCBsP9zCYR7kh8xJr15urQNisgeLylmi7AWe5z83FCC+mFP3q9P8iz8/GpFemMVqSXVQvk3agxMPkIyNwfwqBr5O8nNdIR6RciBOim8pE/O7v2zAXxLK+upjc0JFR4IiM9QaY27aR9Yf7t9Zc5JnoDz3nHxbFThhKqHMnRYk1oxAb4PncJJpcFp2y7bN7gk11FXz4jRV4/fVCxHE6S/x7+eB7OGQC4cR9cI3AYBWzYvqTjspkK/6prUITDRd+ZokgnpxdiKEZ+ISRE1Rih7wpuORf4zCyv/zqbnOQ14pJnAmUun93CnCcu8aIfJwNV+6qFEJ7Tuw0+msir7MxnPQ2fZT2BCK/7zB+eOVp8qXq67FCLk1wxSndN+cn+U+wrqbHwHvdFFuZnIsVU8JzInwEQruGAQI2c6ZA=
  # FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
  - secure: oyB4Y2grIyze2xAwGAasmrlwtO8URWY2y9h7js2SZEOPb/aydZRRSGUoNoGQ12bjfcigsHaZRA//iY5WsrraVzpkneFimiVbfev2mc6aZTSv7z9gRPFrBRwjO5GDQijcrRNaqObXpr1yF6idCCiw6Dep0aq83mNt469k1flSpAIefWEA4LElsLvdcCRS7mz475pVs+5E5v+p2MAuItbRUf8ip4wMqTCH33AjA3CTmgSW8/PLF+YYdQkXYjLzoXGG3QZpr4ts6ixNpHK9mPmdlDefDuorOpyagV7LlNlCmwnmYdwKmtJ/lQyHpwgkqnEy95UIhZ5hgQxEiKgl7YERPU15EfDU2EqgixA0Ua+88ynyQorC8ISJMUcI08JUlcR4MtERlmkzXAkHFPy3nByKr7yn5azt1bi0T+wgTXDVMOUjz4rUSfqmN0aKRY5EP+6Pxcd9SYqzQopYgrpGod23D4Jenxr9b6DrNLYc6uCiNFxk1M7jBvuY+Ht03Tgqf+JRWnL7N7jEBgUga6TErFFIClpsY7Q6MbBu7CQn+AXPVlx9dMg0Cs31Q2ZbKLOdP4aYBTyin/ZyDYxR6d+bQg+qjWn5RVYvc4bUHLql8mP75BoemvzhUEo1lmWtm+FdfzzpK30HPQ0NKkqHF4H23dnk5UIYXiSfpamVGesZrzqD9X0=
